### PR TITLE
showing loading indicator when downloading the map

### PR DESCRIPTION
**Pull request by emre2038**
## Description
Showing a loading indicator when user clicks on map download button.

## Related Issue
https://github.com/OpenUpSA/wazimap-ng-ui/issues/171

## How to test it locally
* run the project
* click on the download map button

## Screenshots
image

### Added
* setup > mapdownlaod.js to handle events and show/hide loading indicator

### Updated
* map > map_download.js to trigger events on button click and download complete

## Checklist

- [x]  🚀 is the code ready to be merged and go live?
- [x]  🛠 does it work (build) locally

### Pull Request

- [x]  📰 good title
- [x]  📝good description
- [x]  🔖 issue linked
- [x]  📖 changelog filled out

### Commits

- [x]  commits are clean
- [x]  commit messages are clean

### Code Quality

- [x]  🚧 no commented out code
- [x]  🖨 no unnecessary logging
- [x]  🎱 no magic numbers
- [ ]  ⚙️ ran jslint
- [ ]  🧰 ran codeclimate locally

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

### CODE REVIEW

**Review by milafrerichs — CHANGES_REQUESTED** [review]
can you make sure the loading indicator is visible once you click the icon. 
maybe run the download with `requestAnimationFrame` to make sure the icon is changed before we block the execution.

**Comment by emre2038** [comment]
@milafrerichs `requestAnimationFrame` doesn't fix this(it maybe my fault - not 100% sure) but `setTimeout` with 0 delay works. I know it is not a good way. what would you recommend?

**Comment by milafrerichs** [comment]
> @milafrerichs `requestAnimationFrame` doesn't fix this(maybe I'm doing something wrong - not 100% sure) but `setTimeout` with 0 delay works. I know it is not a good way. what would you recommend?

let's go with `setTimeout` can you use `1` instead of 0 it seems 0 does not work in firefox all the time. 
thanks

**Comment by emre2038** [comment]
@milafrerichs done 👍

**Review by milafrerichs — APPROVED** [review]
I would have put the timeout somewhere else. but it's good to go.

**Pull request merged**
