### PR TITLE
updated point facilities so it matches the design

### PR DESCRIPTION
**Pull request by emre2038**

### CODE REVIEW

**Comment by adieyal** [comment]
Merged but it doesn't seem to reflect on github

**Comment by emre2038** [comment]
[Update point facilities to match design on rich data view](https://trello.com/c/1XjxqEXQ/438-update-point-facilities-to-match-design-on-rich-data-view)

**Comment by emre2038** [comment]
[Updated location facilities area](https://trello.com/c/jj17DN7h/437-updated-location-facilities-area)

**Comment by emre2038** [comment]
[Ensure label truncation on charts works as per the design](https://trello.com/c/hS8Mg2BE/434-ensure-label-truncation-on-charts-works-as-per-the-design)

**Pull request closed without merging**
