### PR TITLE
Refactored HTMLBlock code

### PR DESCRIPTION
**Pull request by adieyal**
## Description
Refactored the HTMLBlock code to handle qualitative data.

1. Qualitative data is now handled correctly
2. HTML descriptions now work
3. Code that handles metadata, title, and description was pushed to the ContentBlock parent class

## Related Issue
https://trello.com/c/E9XN4wrh/803-rich-text-descriptions-as-a-user-i-would-like-to-be-able-to-click-links-in-descriptions-and-read-them-easily-so-that-i-can-more

## How to test it locally
1. Create a qualitative variable in the backend 
2. Add an html description
3. View the rich data view ensure that it is being represented correctly.

## Checklist

- [X]  🚀 is the code ready to be merged and go live?
- [X]  🛠 does it work (build) locally
- [X] 👩‍🎨 does the design matches the [Demo](https://wazimap-ng-v1.webflow.io/demo)

### Pull Request

- [X]  📰 good title
- [X]  📝good description
- [X]  🔖 issue linked
- [ ]  📖 changelog filled out
- [X] commit messages are meaningful

### Code Quality

- [X]  🚧 no commented out code
- [X]  🖨 no unnecessary logging
- [X]  🎱 no magic numbers

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

### CODE REVIEW

**Comment by adieyal** [comment]
[rich text descriptions (Backend) | As a user I would like to be able to click links in descriptions and read them easily so that I can more easily consume the descriptions that can become quite verbose](https://trello.com/c/L3IHPUjP/861-rich-text-descriptions-backend-as-a-user-i-would-like-to-be-able-to-click-links-in-descriptions-and-read-them-easily-so-that-i-c)

**Comment by adieyal** [comment]
[rich text indicator | As a user I would like to find qualitative data like audit outcomes and links to important documents specific to a geography so that I can see qualitative data just like I can see quantitiative data](https://trello.com/c/XDzZvYXd/802-rich-text-indicator-as-a-user-i-would-like-to-find-qualitative-data-like-audit-outcomes-and-links-to-important-documents-specifi)

**Comment by adieyal** [comment]
[rich text descriptions (Frontend) | As a user I would like to be able to click links in descriptions and read them easily so that I can more easily consume the descriptions that can become quite verbose](https://trello.com/c/E9XN4wrh/803-rich-text-descriptions-frontend-as-a-user-i-would-like-to-be-able-to-click-links-in-descriptions-and-read-them-easily-so-that-i)

**Review by michaelglenister — APPROVED** [review]
Read through the changes, looks good to me

**Pull request merged**
