### PR TITLE
show login modal for private profiles

### PR DESCRIPTION
**Pull request by waracci**
## Description

For profiles marked private a login modal should be shown
401 in request log which I think is supposed to trigger login prompt
"Another login already sent" in the console log
no login prompt
## How to test it locally

Find a private profile, if none, change the settings for a profile on stage, and the modal should show up requiring you to log in.

## Screenshots
Login modal without close button

Screenshot from 2021-07-14 14-26-32

### Removed forgot password label
Screenshot from 2021-07-15 12-47-07

### CODE REVIEW

**Comment by michaelglenister** [comment]
Good start, this fixes the core issue. I don't think it should possible to close the modal without logging in and there is some unnecessary logging that needs to be cleaned up

**Comment by waracci** [comment]
> Good start, this fixes the core issue. I don't think it should possible to close the modal without logging in and there is some unnecessary logging that needs to be cleaned up

Implemented.

**Comment by waracci** [comment]
> > Good start, this fixes the core issue. I don't think it should possible to close the modal without logging in and there is some unnecessary logging that needs to be cleaned up
> 
> Implemented.

**Comment by waracci** [comment]
oops, closed by mistake.

**Pull request merged**
