### PR TITLE
design changes of add filter button

### PR DESCRIPTION
**Pull request by emre2038**
## Description
modifying choropleth add filter button

## Related Issue
https://trello.com/c/f3ogmTOu/841-common-add-filter-button-for-data-mapper-and-rich-data-view-people-are-finding-it-easy-to-use-the-data-mapper-add-filter-button

## How to test it locally
* select any subindicator from the data mapper
* when the choropleth is displayed, confirm that instead of `add filter button`, there is a `+` button  and it is working

## Screenshots
image

### Updated
* `index.html`, `webflow.js`, `webflow.css` to apply the design changes
* `mapchip.js` to update the code that manages the button

## Checklist

- [x]  🚀 is the code ready to be merged and go live?
- [x]  🛠 does it work (build) locally
- [x] 👩‍🎨 does the design matches the [Demo](https://wazimap-ng-v1.webflow.io/demo)

### Pull Request

- [x]  📰 good title
- [x]  📝good description
- [x]  🔖 issue linked
- [x]  📖 changelog filled out
- [x] commit messages are meaningful

### Code Quality

- [x]  🚧 no commented out code
- [x]  🖨 no unnecessary logging
- [x]  🎱 no magic numbers

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [x]  ✅ ran tests locally & are passing

### CODE REVIEW

**Comment by emre2038** [comment]
[common add filter button | for data mapper and rich data view - people are finding it easy to use the data mapper add filter button and a bit tricky to find the rich data one [Est:](https://trello.com/c/f3ogmTOu/841-common-add-filter-button-for-data-mapper-and-rich-data-view-people-are-finding-it-easy-to-use-the-data-mapper-add-filter-button)

**Comment by waracci** [comment]
Screenshot from 2021-07-13 10-51-49
The wazimap-ng.webflow.css file is missing in your code, make sure is exists and is referenced properly.

**Comment by emre2038** [comment]
should be fixed now @waracci

**Comment by adieyal** [comment]
@emre2038 could you have a look at the conflicts?

**Comment by waracci** [comment]
The Point legend is missing when I select a dataset in the services mapper tab.

**Comment by emre2038** [comment]
Matt will fix the point legend issue than I'll fix the conflicts. FYI @waracci @adieyal

**Comment by adieyal** [comment]
@emre2038 could you please resolve these conflicts so that I can review the PR?

**Comment by adieyal** [comment]
@emre2038 could you update this with the latest webflow export

**Comment by emre2038** [comment]
this PR isn't relevant anymore @adieyal . this PR was created before the filter refactoring and the current staging already contains the button design change

**Pull request closed without merging**
