### PR TITLE
webflow export june 2021

### PR DESCRIPTION
**Pull request by waracci**
## Description

Contains a few key changes.

1. No console errors:
Screenshot from 2021-06-28 17-42-41

2. Geo tooltip geo type field has been updated
Screenshot from 2021-06-28 17-38-34

3. Mapchip titles now shown in full
Screenshot from 2021-06-28 17-34-19

## Related Issue

https://trello.com/c/NBD1TifL/829-fix-wrapping-of-geo-tooltip-geo-type-field-timebox-2-hours

## How to test it locally

Run branch locally and verify that the expected changes are present.

## Changelog

https://app.gitbook.com/@openup/s/wazi-ng-technical/development-process/changelog#06-28-2021-location-tag-width

## Checklist

- [ ]  🚀 is the code ready to be merged and go live?
- [ ]  🛠 does it work (build) locally
- [ ] 👩‍🎨 does the design matches the [Demo](https://wazimap-ng-v1.webflow.io/demo)

### Pull Request

- [ ]  📰 good title
- [ ]  📝good description
- [ ]  🔖 issue linked
- [ ]  📖 changelog filled out
- [ ] commit messages are meaningful

### Code Quality

- [ ]  🚧 no commented out code
- [ ]  🖨 no unnecessary logging
- [ ]  🎱 no magic numbers

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

### CODE REVIEW

**Comment by waracci** [comment]
[Fix wrapping of geo tooltip geo type field [timebox 2 hours]](https://trello.com/c/NBD1TifL/829-fix-wrapping-of-geo-tooltip-geo-type-field-timebox-2-hours)

**Review by michaelglenister — COMMENTED** [review]
The wrapping issue is fixed in the deploy preview
However, the map chip filters seem to be missing

**Comment by jbothma** [comment]
> The wrapping issue is fixed in the deploy preview
> However, the map chip filters seem to be missing

Verified.

Screenshot_2021-07-01_17-56-38

**Comment by michaelglenister** [comment]
I've also come across this, charts with a lot of data don't seem to be hiddden/shortened properly behind the "load more rows" buttons
webflowjune

**Comment by emre2038** [comment]
* `.map-options__filters_content` div should be removed from `styles` section
* `.dropdown-menu__trigger` elements do not need the `.disabled` class because the `.mapping-options__filter` elements, which are the parents of the trigger elements, already have the `.disabled` class.
* as @michaelglenister has already mentioned too, `load more rows` is not positioned correctly in rich data panel tables

**Comment by waracci** [comment]
> * `.map-options__filters_content` div should be removed from `styles` section
> * `.dropdown-menu__trigger` elements do not need the `.disabled` class because the `.mapping-options__filter` elements, which are the parents of the trigger elements, already have the `.disabled` class.
> * as @michaelglenister has already mentioned too, `load more rows` is not positioned correctly in rich data panel tables

@emre2038 I'll be looking into this.

**Comment by michaelglenister** [comment]
Looks like the filter and tables were fixed, I didn't find any other issues

**Comment by emre2038** [comment]
@waracci looks like `.dropdown-menu__trigger` in `.styles` section still has `.disabled` class. we use that element to clone and create the dropdowns in rich data panel.

steps to reproduce : 
* expand the rich data panel
* on any chart click `+` button to add a new filter row
* on the new filter row select an attribute
* value dropdown is not clickable because of the `.disabled` class

**Comment by waracci** [comment]
> dropdown-menu__trigger

I can confirm that it was not removed in the export. I removed it and I will also inform Matt of the change.

**Comment by emre2038** [comment]
it looks good to me now

**Comment by waracci** [comment]
[wrap long text in table cells](https://trello.com/c/wren9Nqs/840-wrap-long-text-in-table-cells)

**Comment by waracci** [comment]
[Fix unnecessary truncation of data selection in mapchip [timebox 2 hours]](https://trello.com/c/FqkeeS6D/814-fix-unnecessary-truncation-of-data-selection-in-mapchip-timebox-2-hours)

**Review by adieyal — APPROVED** [review]

**Pull request merged**
