### PR TITLE
applying tooltip design changes, showing facility modal

### PR DESCRIPTION
**Pull request by emre2038**
## Description
Applied design changes related with tooltip. Used the export Matt has created and attached here : 
https://trello.com/c/7hIyV9Lu/633-facility-tooltip-and-facility-modal

Using the `More Info` button on the tooltips, a modal could be viewed.

## Related Issue
https://github.com/OpenUpSA/wazimap-ng-ui/issues/186

## How to test it locally
* On the point mapper window select a category 
* When the points are loaded into the map test if the point tooltips look as designed and if the data shown on them are correct
* Click `More Info` button on any tooltip and test if the modal looks as designed and if the data shown on it is correct

## Screenshots
image

edit - Jan 22, 2021
image

### Updated
* utils.js. when we implemented the tooltips initially we had a hard time because of pre-defined leaflet classes. so instead of applying the css classes that Matt has created to tooltips directly, we instead applied those classes' properties to the pre-defined classes. while working on this issue I figured out why pre-defined classes break the design and applied the css classes that Matt has created. `setPopupStyle()` function can be implemented as css too.
* point_data.js to populate facility modal using the data of the selected point, to apply desing changes and utils.js related changes
* popup.js to apply design changes and utils.js related changes

## Checklist

- [x]  🚀 is the code ready to be merged and go live?
- [x]  🛠 does it work (build) locally
- [x] 👩‍🎨 does the design matches the [Demo](https://wazimap-ng-v1.webflow.io/demo)

### Pull Request

- [x]  📰 good title
- [x]  📝good description
- [x]  🔖 issue linked
- [x]  📖 changelog filled out
- [x] commit messages are meaningful

### Code Quality

- [x]  🚧 no commented out code
- [x]  🖨 no unnecessary logging
- [x]  🎱 no magic numbers

### Testing

- [ ]  ✅ added (appropriate) unit tests
- [ ]  💢 edge cases in tests were considered
- [ ]  ✅ ran tests locally & are passing

### CODE REVIEW

**Comment by emre2038** [comment]
@milafrerichs while applying the new design and css classes I had to change popup offset from `-10` to `20`. do we count this as a magic number?

**Comment by milafrerichs** [comment]
> @milafrerichs while applying the new design and css classes I had to change popup offset from `-10` to `20`. do we count this as a magic number?

yes, indeed :)

**Comment by emre2038** [comment]
what should we do instead?

this offset value is needed because otherwise the popup is created away from the cursor.

**Comment by milafrerichs** [comment]
> what should we do instead?
> 
> this offset value is needed because otherwise the popup is created away from the cursor.

create a new variable: `POPUP_OFFSET`

**Comment by emre2038** [comment]
I thought that would count as a magic number too - ok

**Comment by milafrerichs** [comment]
no, magic numbers are just numbers without context. 
so essentially every time there is a number and it is not assigned to a variable it is a magic number, because you don't know the meaning. most of the time, that is not a big deal but can lead to a lot of confusion. 
why 10 and not -5 fo example. what is that number for.

**Comment by emre2038** [comment]
created `POPUP_OFFSET` variable, made the necessary change to remove tooltip rows

**Review by milafrerichs — APPROVED** [review]

**Pull request merged**
